-- adempiere.z_data_dfs_view source

CREATE OR REPLACE VIEW adempiere.z_data_dfs_view
AS SELECT z_tbl_dfs_tampung.ad_client_id,
    z_tbl_dfs_tampung.ad_org_id,
    z_tbl_dfs_tampung.orgdepoid,
    z_tbl_dfs_tampung.datedoc,
    z_tbl_dfs_tampung.ad_user_id,
    z_tbl_dfs_tampung.organization,
    z_tbl_dfs_tampung.createddate,
    z_tbl_dfs_tampung.createdby AS createby,
    z_tbl_dfs_tampung.completedate,
    z_tbl_dfs_tampung.completeby,
    z_tbl_dfs_tampung.documentdate,
    z_tbl_dfs_tampung.timeslotstart,
    z_tbl_dfs_tampung.documentno,
    z_tbl_dfs_tampung.deskripsi,
    z_tbl_dfs_tampung.m_warehouse_id,
    z_tbl_dfs_tampung.c_project_id,
    z_tbl_dfs_tampung.birdage_day,
    z_tbl_dfs_tampung.birdage_week,
    z_tbl_dfs_tampung.light,
    z_tbl_dfs_tampung.water,
    z_tbl_dfs_tampung.temp_min,
    z_tbl_dfs_tampung.temp_max,
    z_tbl_dfs_tampung.humidity,
    z_tbl_dfs_tampung.abw,
    z_tbl_dfs_tampung.uniformity,
    z_tbl_dfs_tampung.docstatus,
    z_tbl_dfs_tampung.koreksi,
    z_tbl_dfs_tampung.z_good_issue_id,
    z_tbl_dfs_tampung.z_good_receipt_id,
    z_tbl_dfs_tampung.deskripsi_line,
    z_tbl_dfs_tampung.m_product_id,
    z_tbl_dfs_tampung.warehouse_storage,
    z_tbl_dfs_tampung.qty,
    z_tbl_dfs_tampung.c_uom_id,
    z_tbl_dfs_tampung.waktu,
    z_tbl_dfs_tampung.statusval,
    z_tbl_dfs_tampung.dfs_awal,
    z_tbl_dfs_tampung.diff_date
   FROM z_tbl_dfs_tampung;